apiVersion: v1
kind: Secret
metadata:
  name: web-dvwa
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZHZ3YQ==
  MYSQL_DATABASE: ZHZ3YQ==
  MYSQL_USER: ZHZ3YQ==
  MYSQL_PASSWORD: cEBzc3cwcmQ=
  DB_SERVER: d2ViLWR2d2EtZGItc3Zj