{{- if .Values.istio.enabled -}}
{{- $fullName := include "web-dvwa.fullname" . -}}
{{- $svcPort := .Values.web_service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: web-dvwa-gateway
spec:
  selector:
    {{ .Values.istio.selector_key | nindent 4 }}: {{ .Values.istio.selector_value }}
  servers:
  - port:
      number: {{ $svcPort }}
      name: http
      protocol: HTTP
    {{- range .Values.istio.hosts }}
    hosts:
    - {{ .host | quote }}
    {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-dvwa
spec:
  {{- range .Values.istio.hosts }}
  hosts:
  - {{ .host | quote }}
  {{- end }}
  gateways:
  - web-dvwa-gateway
  http:
  - route:
    - destination:
        port:
          number: {{ $svcPort }}
        host: web-dvwa-service
{{- end }}