apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dvwa-web
spec:
  selector:
    matchLabels:
      app: web-dvwa-web
  template:
    metadata:
      labels:
        app: web-dvwa-web
    spec:
      volumes:
        - name: create-db
          secret:
            secretName: create-db
      containers:
      - name: web-dvwa-web
        image: "{{ .Values.web_image.repository }}:{{ .Values.web_image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: web-dvwa
      initContainers:
      - name: create-db
        image: "{{ .Values.db_image.repository }}:{{ .Values.db_image.tag | default .Chart.AppVersion }}"
        command: ["/bin/sh"]
        args: ["-c", "mysql -h web-dvwa-db-svc -u dvwa -pp@ssw0rd dvwa < /etc/create-db/create-sql"]
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: create-db
            mountPath: "/etc/create-db"
      