apiVersion: v1
kind: Service
metadata:
  name: web-dvwa-service
spec:
  selector:
    app: web-dvwa-web
  ports:
  - port: {{ .Values.web_service.port }}
    targetPort: {{ .Values.web_service.port }}
  type: {{ .Values.web_service.type }}